### PR TITLE
Refactor of Bump Commands

### PR DESCRIPTION
**Pull request by marky291**

### CODE REVIEW

**Comment by marky291** [comment]
Did not update tests, Will do shortly, I have however tested this and it works perfect.

**Comment by marky291** [comment]
New tests to match new code added, seems the checks don't look at my tests, but rather whats in the repository, so please ignore it.

**Comment by talevskiigor** [comment]
Sorry for late answer, but i got flu this days...i hope i will merge it for the weekend. Thanks for your effort.

**Comment by marky291** [comment]
Oh.. No problem, I was using this package, and sometimes I bumped twice by accident, or bumped the wrong thing, or decided to change my mind and go back, but the only way to correct this was to edit the version in composer.json, which wasn't very clear to me either, this hopefully will benefit people.

**Comment by talevskiigor** [comment]
Hi CrushCandy,
i just update the package and add undo option... thanks for the inspiration and sorry i don't accept your PR cos it was to much changes... but i add functionality by your sugestion.

**Comment by CrushCandy** [comment]
I find my changes more clean and readable but if that's your choice, then so be it.

**Pull request closed without merging**
